In [30]:
import pandas as pd
import requests
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
url = 'https://raw.githubusercontent.com/Kinetic-Drive/HackGT8/main/data-processing/data.csv'
df = pd.read_csv(url)
print(df)

    Index                          Name  ... Rating type
0       0  Aristocles Innerspring Queen  ...   4.70   fs
1       1                   Bournemouth  ...   4.26   fs
2       2                      Cheshire  ...   4.85   fs
3       3                    Derryclone  ...   3.51   fs
4       4                         Espey  ...   4.14   fs
5       5                         Hagen  ...   3.19   fs
6       6                       Inshore  ...   3.06   fs
7       7                         Kasey  ...   4.11   fs
8       8                      Kittrell  ...   4.49   fs
9       9                         Sonya  ...   3.44   fs
10     10                   Walton Lane  ...   4.02   fs
11     11      Clairsville Leather Sofa  ...   4.30   ls
12     12               Gardner Leather  ...   4.88   ls
13     13             Hawthorne Leather  ...   3.11   ls
14     14         Molly Premium Italian  ...   4.79   ls
15     15                    Pratt Sofa  ...   4.21   ls
16     16                      

In [31]:
inputs = df.drop(columns =['type', 'Index', 'Name'])
target = df['Index']

In [32]:
from sklearn.preprocessing import LabelEncoder

In [33]:
le_color = LabelEncoder()
le_price = LabelEncoder()
le_size = LabelEncoder()
le_requires_assembly = LabelEncoder()
le_country_of_origin = LabelEncoder()
le_rating = LabelEncoder()

In [34]:
inputs['color_n'] = le_color.fit_transform(inputs['Color'])
inputs['price_n'] = le_price.fit_transform(inputs['Price'])
inputs['size_n'] = le_size.fit_transform(inputs['Size'])
inputs['ra_n'] = le_requires_assembly.fit_transform(inputs['Requires Assembly'])
inputs['coo_n'] = le_country_of_origin.fit_transform(inputs['Country of Origin'])
inputs['rating_n'] = le_rating.fit_transform(inputs['Rating'])
inputs.head()

Color     Price  Size Requires Assembly  ... size_n  ra_n  coo_n  rating_n
0       Pink  $730.99     65               Yes  ...     15     1      5        32
1  Dark Grey  $716.99     70               Yes  ...     19     1     13        24
2  Dark Grey  $370.99     67               Yes  ...     17     1     13        35
3     Yellow  $465.99     55                No  ...      9     0     13         8
4      White  $720.99     55                No  ...      9     0      3        22

[5 rows x 12 columns]

In [35]:
inputs_n = inputs.drop(['Color', 'Price', 'Size', 'Requires Assembly', 'Country of Origin', 'Rating'], axis = 'columns')
inputs_n

color_n  price_n  size_n  ra_n  coo_n  rating_n
0        13       38      15     1      5        32
1         5       35      19     1     13        24
2         5       15      17     1     13        35
3        19       25       9     0     13         8
4        17       36       9     0      3        22
5         0       28      20     1      2         4
6        10       40      16     1     14         0
7        17       41      19     1     14        21
8         1       33      18     0      1        27
9        14       16      11     1     11         6
10        8       34      13     1     14        17
11        1       22      13     0     14        25
12        4       37      13     1      1        36
13       18       39      14     1      1         2
14        0       42      19     0      8        33
15       14       23      15     1     14        23
16        6       26       3     1      1        37
17       12        1       9     1      4        14
18        9       14       9     1      1        31
19        0       31       1     1      1        31
20       15       32       3     0     10         3
21       17       32      15     0      7        13
22       17        8       9     1     10        30
23       15       29      15     1      4        18
24       17       19      11     1      4        34
25       17        1       4     1     14        29
26        9       27       6     1     14        33
27       17       21       6     1      6        25
28        3        5       1     0     14        16
29       15       12       0     0     14         5
30        1       13       6     1      1        22
31       17        7       3     0     12        11
32        2        6       2     0     13        19
33        6        9       1     0     14        28
34       11       24      13     1     14        10
35        9       20       6     1      1        32
36       16       10       5     0      8         9
37        0       17       7     1      0         7
38        6       18      11     1     13         1
39       11        0       9     0      1        17
40        6        2       8     1      1        15
41        1       30       9     0      9        12
42        1        3      10     0     13        16
43        7       11      13     1     14        20
44        9        4      12     1     14        26

In [36]:
A_sparse = sparse.csr_matrix(inputs_n)
similarities = cosine_similarity(A_sparse)
print('pairwise dense output:\n {}\n'.format(similarities))


similarities_sparse = cosine_similarity(A_sparse,dense_output=False)
print('pairwise sparse output:\n {}\n'.format(similarities_sparse))

pairwise dense output:
 [[1.         0.96357803 0.87841657 ... 0.68704057 0.86063682 0.75376419]
 [0.96357803 1.         0.88194661 ... 0.75961293 0.89543471 0.75290025]
 [0.87841657 0.88194661 1.         ... 0.93295584 0.9691956  0.95516232]
 ...
 [0.68704057 0.75961293 0.93295584 ... 1.         0.94963007 0.95724907]
 [0.86063682 0.89543471 0.9691956  ... 0.94963007 1.         0.95972223]
 [0.75376419 0.75290025 0.95516232 ... 0.95724907 0.95972223 1.        ]]

pairwise sparse output:
   (0, 37)	0.9220094247512006
  (0, 19)	0.9292411127261095
  (0, 14)	0.9675552317355182
  (0, 5)	0.8056879395534511
  (0, 44)	0.7537641912062004
  (0, 43)	0.8606368176082229
  (0, 42)	0.6870405734216376
  (0, 41)	0.9196404508156877
  (0, 40)	0.7773220743364717
  (0, 39)	0.6937841338202378
  (0, 38)	0.7469670987003343
  (0, 36)	0.8040483924136889
  (0, 35)	0.9460116994039397
  (0, 34)	0.8954062660308311
  (0, 33)	0.7867529332718739
  (0, 32)	0.7432884719060713
  (0, 31)	0.7100643174321418
  (0, 30)	0.92